#!/bin/bash

model=$(sysctl -n hw.targettype)

jetsam_plist="/System/Library/LaunchDaemons/com.apple.jetsamproperties.${model}.plist"

if [[ ! -f "${jetsam_plist}" ]];then
    echo "Error: Couldn't find the jetsam properties plist (${jetsam_plist})"
    exit 1
fi

# The new upper memory limit for com.apple.Safari.content-blocker
new_limit=256

plutil -key Version4 -key Extension -key Override -key com.apple.Safari.content-blocker -key ActiveHardMemoryLimit -value ${new_limit} $jetsam_plist
plutil -key Version4 -key Extension -key Override -key com.apple.Safari.content-blocker -key InactiveHardMemoryLimit -value ${new_limit} $jetsam_plist

# The new upper memory limit for com.apple.SafariServices.ContentBlockerLoader
new_limit=384

plutil -key Version4 -key XPCService -key Override -key com.apple.SafariServices.ContentBlockerLoader -key ActiveSoftMemoryLimit -value ${new_limit} $jetsam_plist
plutil -key Version4 -key XPCService -key Override -key com.apple.SafariServices.ContentBlockerLoader -key InactiveHardMemoryLimit -value ${new_limit} $jetsam_plist

echo "A reboot or ldrestart IS REQUIRED for the memory limit change to take effects"